# fly.toml app configuration file generated for disc-clone-backend on 2023-09-16T04:12:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "disc-clone-backend"
primary_region = "otp"

[http_service]
  internal_port = 1999
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
